### ISSUE TITLE
Wokwi for VS Code fails to start with an empty [[net.forward]] section in wokwi.toml

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-features#1014]
**Describe the bug**

Wokwi for VS Code fails to start with an empty `[[net.forward]]` section in wokwi.toml

**To Reproduce**

Create a wokwi.toml file with the following content:

```toml
[wokwi]
version = 1
elf = "firmware.elf"
firmware = "firmware.bin"

[[net.forward]]
```

Then try to start Wokwi, but nothing will happen.

**Expected behavior**

The "Wokwi Simulator" tab opens and the simulation begins.

**Additional context**

Initially reported on discord: https://discord.com/channels/787627282663211009/1380843976793260053
