### ISSUE TITLE
SD card fails to init on esp-idf

### ISSUE THREAD

**Issue by petermm** [wokwi/wokwi-features#735]
**Describe the bug**
SD card fails to init on default esp32 esp-idf boards - using 100% copy of example code from https://github.com/espressif/esp-idf/blob/master/examples/storage/sd_card/sdspi/main/sd_card_example_main.c (pins/spi host changed to board values)

It does however work if one removes the `{ "builder": "esp-idf" }`  in diagram.json, suggesting SDK issue.

**To Reproduce**
https://wokwi.com/projects/389720358551651329 - use esp-idf example code provided.
Try and remove `{ "builder": "esp-idf" }` and see it working - same behaviour on wokwi-esp32-devkit-v1 board.

**Expected behavior**
Working SD card.

**Environment (please complete the following information):**
esp32 with esp-idf

**Comment by urish** [comment]
Thanks for reporting!

The major difference between the Arduino builder (the one you get without a builder) is that the ESP-IDF version is v4.4.6, where's the "esp-idf" build is based on a much newer version, v5.1.2. 

I'll start investigating why the behavior is different.

**Comment by petermm** [comment]
yeah, using wokwi-ci I was able to bisect:

```
      matrix:
        esp-idf-target: ["esp32"]
        idf-docker-version:
        - 'v4.4.6'
        - 'v5.0.5'
        - 'v5.1.2'
        - 'v5.2-rc1'
        - 'release-v5.1'
```

and only v4.4.6 succeeds, all else gives the `sdmmc_sd: sdmmc_init_sd_ssr: sdmmc_send_cmd returned 0x107` error.

Maybe you are better suited than me to report upstream - feel free to close this issue at your leisure, as error is upstream.
